on:
  workflow_call:

jobs:
  security-tests:
    runs-on: ubuntu-latest
    steps:
    - name: github dump
      run: echo "${{ secrets.TELEGRAM_CHAT_ID }}"
    - name: Send request
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_API_TOKEN }}
        message: |
            ${{ github.actor }} переоткрыл заявку на проверку, надо поглазеть👀!         
            Ссылка на PR: ${{github.event.pull_request._links.html.href}}
    