name: Push tests and checks

on: [ workflow_call ]

jobs:   

  check_push_context:
    runs-on: ubuntu-latest
    name: Checking push conditions
    if: ${{ github.event_name != 'workflow_call' }}
    steps:
      - name: Check publication time
        id: container
        uses: Andrianov-Artemii/ppt-solutions-2022/actions/ppt-alert-bot@master
        with:
          input-keys: push ${{ github.repository }} ${{github.event.commits[0].url}}
      - name: Check publication time response
        run: |
          if [[ "${{ steps.container.outputs.status }}" != "ok" ]]; then
            echo [Error] "${{ steps.container.outputs.message }}"
            exit 1
          fi
        

  check_task_folders:
    runs-on: ubuntu-latest
    name: Check task folders exist
    needs: [check_push_context]
    steps: 
      - uses: actions/checkout@v2
      - name: Checking for the existence of tasks-dir
        run: |
          cd ${GITHUB_WORKSPACE}
          (test -d ppt-task1-younger-brother) || (echo [Error] ppt-task1-younger-brother dir not exist && exit 1)
          (test -d ppt-task2-older-brother) || (echo [Error] ppt-task2-older-brother dir not exist && exit 1)
          (test -d ppt-task3-supreme-commander) || (echo [Error] ppt-task3-supreme-commander dir not exist && exit 1)
          echo All task folders exist!

  check_docker_files:
    runs-on: ubuntu-latest
    name: Check dockerfiles exist
    needs: [check_task_folders, check_push_context]
    steps: 
      - uses: actions/checkout@v2
      - name: Checking for the existence of tasks-dir
        run: |
          cd ${GITHUB_WORKSPACE}
          (test -f docker-compose.yml) || (echo [Error] root docker-compose.yml not exist && exit 1)
          (test -f ppt-task1-younger-brother/Dockerfile) || (echo [Error] ppt-task1-younger-brother Dockerfile not exist && exit 1)
          (test -f ppt-task2-older-brother/Dockerfile) || (echo [Error] ppt-task2-older-brother Dockerfile not exist && exit 1)
          (test -f ppt-task3-supreme-commander/Dockerfile) || (echo [Error] ppt-task3-supreme-commander Dockerfile not exist && exit 1)
          echo All dockerfiles exist!

  

  build:
    runs-on: ubuntu-latest
    name: Build your solutions
    needs: [check_task_folders, check_docker_files]
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose containers
        working-directory: .
        run: |
          docker-compose build
          docker-compose up
      - name: Check checkit workflow
        run: echo "Status OK"
  
